site_name: IA & Jeux vidéos

markdown_extensions:
  - admonition
  - pymdownx.details # allows admonition collapsible
  - pymdownx.superfences # allows nesting of code
  - toc # table of content
  - mdx_math # python-markdown-math
  - pymdownx.arithmatex: # Arithmatex to preserves LaTeX for being used with MathJax
     generic: true
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.tasklist: # support checkboxes
       custom_checkbox: true
       clickable_checkbox: true

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate

plugins:
  - search
  - section-index
  - exclude:
      glob:
        - machine learning/ancien/*

nav:
- Acceuil: "index.md"
- Pré-requis:
  - Installation & gestion de python:
    - "Outils pour la data science": "installation_python_simple.md"
#   - Deep Learning:
#     - "Outils pour le deep learning": "deep learning/installation_stack_dl.md"

- Intelligence Artificielle & Jeux vidéos:
  - "Chapitre 1: Découverte de l'IA": "decouverte_IA.md"
  - "Chapitre 2: Tour d'horizon de l'IA dans les JV": "tour_horizon_IA_&_JV.md"
  - "Chapitre 3: Agents intelligents": "agents_intelligents.md"
  - "Chapitre 4: Résolution de problèmes dans les jeux": "resolution_problemes_appliquée_au_jeux.md"

- Ressources additionnelles:
#   - Lexique: 
#     - ressources additionnelles/lexique/index.md
#     - "Lexique des notions importantes": "ressources additionnelles/lexique/lexique_general_datascience_IA.md"
  - Elements de cours: 
    - ressources additionnelles/elements_cours/index.md
    - "Pour continuer votre formation": "ressources additionnelles/elements_cours/ressources_datascience_IA.md"
#   - Quelques conseils & astuces : "ressources additionnelles/methodologie/conseils_méthodologiques.md"

- Evaluations:
  - "Projet 1: Pac Man multi agent": "evaluations/Projet1_multiagent_pacman.md"
